<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>better_ik</AssemblyName>
		<PackageId>better_ik</PackageId>
		<LangVersion>14</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX</DefineConstants>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<OutputPath>D:/SteamLibrary/steamapps/common/sbox/.vs/output/</OutputPath>
		<DocumentationFile>D:/SteamLibrary/steamapps/common/sbox/.vs/output/better_ik.xml</DocumentationFile>
		<RootNamespace>Sandbox</RootNamespace>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
		<Using Include="Microsoft.AspNetCore.Components" />
		<Using Include="Microsoft.AspNetCore.Components.Rendering" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.CodeUpgrader.dll"/> 
		<Analyzer Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Generator.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.System.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Engine.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Filesystem.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Reflection.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Mounting.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Microsoft.AspNetCore.Components.dll"/> 
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="D:/SteamLibrary/steamapps/common/sbox/addons/base/code/Base Library.csproj" />
	</ItemGroup>

</Project>
